### ISSUE TITLE
Android N does not take picture

### ISSUE THREAD

**Issue by poldz123** [google/cameraview#126]
I am using the nexus 6p device with android N 7.1.1, but when I take am image it does not call the callback on `onPictureTaken`, could this be a bug or this library only supports 24 and below?

**Comment by yaraki** [comment]
The library does support Nougat. It is working fine on my Nexus 5X and Pixel. Please attach a bug report so I can investigate.

**Comment by ShreyashPromact** [comment]
@poldz123 
It is working fine. Make sure you are using latest library for same.

Sincerely,
Shreyash
