### ISSUE TITLE
Android 7.1.2 cameraview not working

### ISSUE THREAD

**Issue by negrogn** [google/cameraview#131]
When trying to use it on a Pixel XL with android 7.1.2, the cameraview is not working. We get a blank screen and when trying to get a pic it crashes. Any known issue?

**Comment by ShreyashPromact** [comment]
I was facing same issue.
It is already resolved. Please let me know the version you are using for that. Make sure you are using the latest library from the repository.

Sincerely,
Shreyash

**Comment by negrogn** [comment]
yes! that fixed the issue. Thanks.
