### ISSUE TITLE
Gradle and Maven link

### ISSUE THREAD

**Issue by XinyueZ** [google/cameraview#134]
Hi, in order to use this library we need link (for build.gradle) to this library.

**Comment by ShreyashPromact** [comment]
@XinyueZ  don't you know how to add library project ?

**Comment by yaraki** [comment]
#10

**Comment by XinyueZ** [comment]
@ShreyashPromact I use library as submodule of library-project.

**Comment by ShreyashPromact** [comment]
@XinyueZ 
When what is wrong with using that way?

Sincerely,
Shreyash

**Comment by XinyueZ** [comment]
@ShreyashPromact It works but not conveniently .

**Comment by janki-vaidya** [comment]
When image is clicked, it comes in a wide angle
