### ISSUE TITLE
How to start the cameraview again after stop?

### ISSUE THREAD

**Issue by SunnyLin2008** [google/cameraview#167]
When i stop the camera one time, and try to start it again,the cameraview can see notting with black background .  How can i start the cameraview again after stop?
Thank`s

**Comment by eth0izzle** [comment]
I had the same problem and couldn't figure out why.  I tried invalidating/redrawing layouts but just couldn't get it to work. My work around for now is programmatically new up the `CameraView `each time - works pretty well. When you call `camera.stop()` make sure to call `removeView(camera)` on it's parent view.

**Comment by SunnyLin2008** [comment]
Thank's eth0izzle.I also  resolution the problem with remove the cameraView befor stop it.
