### ISSUE TITLE
Black CameraView after onResume only in Android 7

### ISSUE THREAD

**Issue by gmerwan** [google/cameraview#183]
Black CameraView after onResume (after onPause) only in Android 7. The camera is taking photo but the view is always black when returning to activity. (ONLY for Android Nougat 7)

**Comment by ukevgen** [comment]
Yes, how we can restore camera in this case?

**Comment by ukevgen** [comment]
Camera on full screen

**Comment by gmerwan** [comment]
Any updates for that ?

**Comment by Gurupreet** [comment]
app is crashing on asus zenfone android 5.0.2  on changing aspect ratio and also showing black screen for some aspect ratio.
thanks

**Comment by jaksab** [comment]
I have this problem too

**Comment by gmerwan** [comment]
We are waiting for an answer or fix ;)

**Comment by serghov** [comment]
same problem

**Comment by smellouk** [comment]
same issue here

**Comment by smellouk** [comment]
same issue

**Comment by smellouk** [comment]
Hi, I notice the black screen is triggered only when the library try to start Camera2. It fails because the device does not support hardware layer, so it will fallback to `Camera1` with `TextureViewPreview`, I think the issue is related to `TextureView`

**"TextureView can only be used in a hardware accelerated window. When rendered in software, TextureView will draw nothing"**

As fix or workaround for that  I adjust `createPreviewImpl` to return `SurfaceViewPreview` when the `CameraView` try to fallback to `Camera1` 

`@NonNull`
`private PreviewImpl createPreviewImpl(Context context, boolean isFallback) {`
`        if(isFallback)`
`            return new SurfaceViewPreview(context, this);`
`        PreviewImpl preview;`
`        if (Build.VERSION.SDK_INT < 14) {`
`            preview = new SurfaceViewPreview(context, this);`
`        } else {`
`            preview = new TextureViewPreview(context, this);`
`        }`
`        return preview;`
`}`

**Comment by yangdingguo** [comment]
I had the same problrem,   VivO x9  7.1.1 I found that  the PowerKey is OK ,but the homeKey do not work well,any one have the resolution?

**Comment by yangdingguo** [comment]
@smellouk   thank you for your advice    but I  7.1.1 use TextureView  ,can you say some detail

**Comment by gmerwan** [comment]
@smellouk Can you provide us with the solution ... I mean the modified Library. 
Thank you.

**Comment by yangdingguo** [comment]
@gmerwan 
public void start() {
        if ( !mImpl.start() ) {
            //store the state ,and restore this state after fall back o Camera1
            Parcelable state = onSaveInstanceState();
            // Camera2 uses legacy hardware layer; fall back to Camera1  then must use Surfaceview ;or black screen
            mImpl = new Camera1(mCallbacks, new SurfaceViewPreview(getContext(), this));

            onRestoreInstanceState(state);
            mImpl.start();
        }
    }

replace the method  in CameraView.Java with this method,maybe  it works well

**Comment by gmerwan** [comment]
@yangdingguo gonna try it ... Thanks ;)

**Comment by smellouk** [comment]
@gmerwan @yangdingguo 
Hey guys, 
I'm using oneplus with android nougat and I was facing the same issue but as I said a fix for that is [here](https://github.com/google/cameraview/issues/183#issuecomment-332142175)

So how you can Implement that ? 
You just need go to the [`CameraView.class`]  and in the line [246](https://github.com/google/cameraview/blob/master/library/src/main/java/com/google/android/cameraview/CameraView.java#L246) and replace this [`createPreviewImpl(getContext())`] by this  [`createPreviewImpl(getContext(), true)`]

**Comment by gmerwan** [comment]
@smellouk  Thank you very much
I already replace it ... gonna test it asap

**Comment by PonnamKarthik** [comment]
Thanks @smellouk  for the solutions its working fine

**Comment by champrocks3190** [comment]
but cameraview class is not editable or writable . it states when try to make change .

**Comment by champrocks3190** [comment]
no option left may be except recreate activity .... 


boolean created=false;

 @Override
    protected void onResume() {
        super.onResume();
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {

                if (created) {
                    recreate();
                }
                cameraView.start();
                created = false;
            }
        }, 100);
    }

    @Override
    protected void onPause() {
        cameraView.stop();
        created = true;
        super.onPause();
    }

**Comment by yangdingguo** [comment]
@smellouk   can you give  somemore code ?  do  you  have  the method  createPreviewImpl(context,boolean) with two parameters?

**Comment by gmerwan** [comment]
@yangdingguo @champrocks3190 
 @smellouk 's solution works well
I tried it and it works.

**Comment by yangdingguo** [comment]
@gmerwan  @champrocks3190  @smellouk    can  you give  the method createPreviewImpl(context,boolean)  ?  now  I  have  no  this method with two parameters

**Comment by yangdingguo** [comment]
@PonnamKarthik 
can you give the method createPreviewImpl(context,boolean) ? now I have no this method with two parameters  ,thank  you

**Comment by gmerwan** [comment]
@yangdingguo use this repo ... I changed the method and you can use it directly.
You can see the changes .. it works.

**Comment by yangdingguo** [comment]
where can  I  see the changes? the source code have changed?

**Comment by yangdingguo** [comment]
@gmerwan   where can I see the changes code  ? the source code have changed?

**Comment by gmerwan** [comment]
sorry this repo https://github.com/gmerwan/cameraview

**Comment by gmerwan** [comment]
@yangdingguo I changed the CameraView.class like @smellouk proposed.
Try it and tell me if there is any problem.

**Comment by GandhiRujul** [comment]
@gmerwan 
when i am stop camera and start it again i am still facing the black screen issue..

**Comment by gmerwan** [comment]
@GandhiRujul I'll see about that. have you tried this repo ?
https://github.com/gmerwan/cameraview
Thank you.

**Comment by GandhiRujul** [comment]
@gmerwan ,  
No I was using that Google Camera.. Its working on your repository thank you so much.

**Comment by gmerwan** [comment]
You're welcome @GandhiRujul

**Comment by GandhiRujul** [comment]
@gmerwan 
I have used your repository but its working almost all devices but I noticed one thing, when I am capturing image in Samsung , Your method `onPictureTaken(CameraView cameraView,byte[] data)` is giving me rotated `byte[]`.  So when I am creating image on based on `byte[]` , I am getting Rotated Image in Samsung device.

**Comment by gmerwan** [comment]
@GandhiRujul for the created image you can rotate it before saving it as a file, I used that somewhere before but forgot it. I suggest u use the camerakit repo:  [https://github.com/CameraKit/camerakit-android](url)
I'm using it personally and it got everything u need + more features u may need too.

As I said there is a way to rotate a bitmap before saving it but that would take more time for you to capture rotate and then save, so try the repo I suggested and tell me you opinion. hope it helps

**Comment by GandhiRujul** [comment]
@gmerwan 
Actually I am not getting bitmap as per aspect ratio in CameraKit , that's why I have decided to change the library to google camera. 

I have already code for rotate bitmap but If I am holding two devices front of face and try to taking capture image (by back camera) so in samsung device i am getting already rotated bitmap(-90 before my rotation of bitmap) where as in nexus device i got the perfect bitmap(0 before my rotation of bitmap).

So after rotation both images orientation will be different than each other.

**Comment by gmerwan** [comment]
@GandhiRujul I understand. I'll see what I can do and respond asap.

**Comment by gmerwan** [comment]
@GandhiRujul  using camerakit I could get either byte array or bitmap object.

**Comment by GandhiRujul** [comment]
@gmerwan 
But I need bitmap into specific aspect ratio so is it possible to set aspect ratio in camera kit ?

**Comment by gmerwan** [comment]
@GandhiRujul Yes it is possible, try to read the manual of CameraKit and try their two apps on Google Play to verify all your needs.

**Comment by yangdingguo** [comment]
@gmerwan   I have seen the code  but I did not  try. I believe it can work well.your method is same with my method,but  we deal it in different   position.

**Comment by GandhiRujul** [comment]
@gmerwan Did you got the issue of samsung device ( byte[] is getting rotated )?

**Comment by pritesh25** [comment]
thanks @smellouk for your efforts
i solved above issue with the help of below code

[tested in actual device] lenovo , honor, samsung, one plus 

pass **true** as a parameter in below method and use that below value as 

    ```
@NonNull
    private PreviewImpl createPreviewImpl(Context context, boolean isFallback) {

        if(isFallback)
            return new SurfaceViewPreview(context, this);

        PreviewImpl preview;
        if (Build.VERSION.SDK_INT < 14) {
            preview = new SurfaceViewPreview(context, this);
        } else {
            preview = new TextureViewPreview(context, this);
        }
        return preview;
    }
```

**Comment by gmerwan** [comment]
@ankuagarwal  Yeah maybe it doesn't use the camera2, but it works perfectly. they moved to version 1.0 so it should be better after the stable version. It is still in dev

**Comment by changjiajie** [comment]
@yangdingguo mImpl = new Camera1(mCallbacks, new SurfaceViewPreview(getContext(), this));
This method returns java.lang.NullPointerException, It is mSurfaceView.getHolder().
Try this solution：
@Override
protected void onResume(){
        if (mCameraRootV != null && mCameraV != null) {
            mCameraRootV.removeView(mCameraV);
            mCameraRootV.addView(mCameraV);
        }
        mCameraV.onResume(mPresent);
}

**Comment by thaodersar** [comment]
Hi I try solution @smellouk shared above and it works. As you said it is workaround solution since TextureView and SurfaceView is just a view for streaming camera preview, and not related when camera 2 failed to start. 

I suppose that the current TextureView still keep streaming with camera hardware when you resume and this time you create a new TextureView with createPreviewImpl. Maybe there is an issue on android 7 that cannot replace the TextureView. I try this solution and it works, resume speed is very quick:

Create an variable to keep textureview instance: PreviewImpl mPreviewImpl;
then modify start like this:

public void start() {
        if (!mImpl.start()) {
            Log.d("Camera2", "start camera 2 fail");
            //store the state ,and restore this state after fall back o Camera1
            Parcelable state=onSaveInstanceState();
            // Camera2 uses legacy hardware layer; fall back to Camera1
//            mImpl = new Camera1(mCallbacks, createPreviewImpl(getContext(), true));
            mImpl = new Camera1(mCallbacks, mPreviewImpl);
            onRestoreInstanceState(state);
            mImpl.start();
        }
    }

Hope this help, I cannot test on other devices & android version so you guys can help

**Comment by chinalwb** [comment]
> Hi I tried solution @smellouk shared above and it works. As you said it is workaround solution since TextureView or SurfaceView is just a view for streaming camera preview, and not related when camera 2 failed to start (I tested screen is black but camera still work).
> 
> I suppose that the current TextureView still keep streaming with camera hardware when you resume and this time you create a new TextureView with createPreviewImpl. Maybe there is an issue on android 7 that cannot replace the TextureView. I try this solution and it works perfectly, resume speed is very quick:
> 
> Create an variable to keep textureview instance: PreviewImpl mPreviewImpl;
> 
> Update CameraView constructor:
> .....
> // Internal setup
> mPreviewImpl = createPreviewImpl(context, false);
> mCallbacks = new CallbackBridge();
> if (Build.VERSION.SDK_INT < 21) {
> mImpl = new Camera1(mCallbacks, mPreviewImpl);
> } else if (Build.VERSION.SDK_INT < 23) {
> mImpl = new Camera2(mCallbacks, mPreviewImpl, context);
> } else {
> mImpl = new Camera2Api23(mCallbacks, mPreviewImpl, context);
> }
> ....
> 
> finally modify start() like this:
> 
> public void start() {
> if (!mImpl.start()) {
> Log.d("Camera2", "start camera 2 fail");
> //store the state ,and restore this state after fall back o Camera1
> Parcelable state=onSaveInstanceState();
> // Camera2 uses legacy hardware layer; fall back to Camera1
> // mImpl = new Camera1(mCallbacks, createPreviewImpl(getContext(), true));
> mImpl = new Camera1(mCallbacks, mPreviewImpl);
> onRestoreInstanceState(state);
> mImpl.start();
> }
> }
> 
> Hope this help, I cannot test on other devices & android versions so you guys can help

You saved me, sir! Thanks very much!
