### ISSUE TITLE
Aspect Ratio not taken into account

### ISSUE THREAD

**Issue by bunjix** [google/cameraview#20]
I have tried with aspectRatio="1:1" but nothing change.

**Comment by yaraki** [comment]
Because it is not one of the supported aspect ratios. We will figure out how to deliver errors properly. For now, please make sure to use CameraView#getSupportedAspectRatios before setting an aspect ratio.

**Comment by ivacf** [comment]
@yaraki so if we always want our camera view to be a square but the camera doesn't support a 1:1 ratio, what's your recommended way to achieve this?

**Comment by yaraki** [comment]
I'll investigate.

**Comment by remq** [comment]
Couldn't you just put the CameraView inside a square parent? Something like this:

```java
public class SquareRelativeLayout extends RelativeLayout {

    public SquareRelativeLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(heightMeasureSpec , heightMeasureSpec );
    }
}
```

**Comment by yaraki** [comment]
That will crop the CameraView to square size, but the taken pictures will not be square.

This is a combination of 2 issues. I'm working on a fix.

- Aspect Ratio is not working properly.
- Nexus 5X reports 1:1 ratio as one of the supported picture format, but the preview crashes with SurfaceView.

**Comment by bunjix** [comment]
@yaraki Do you have any update on this ?

**Comment by yaraki** [comment]
Not yet. I'm working on it.

**Comment by yaraki** [comment]
I added aspect ratio choice in the demo app. Also, setAspectRatio now works after layout. I still need to fix the issue with 1:1 on N5x and such.

**Comment by bolein** [comment]
Nexus 6P, Android Nougat, 1:1 aspect ratio is ignored

**Comment by iftekhar-ahmed** [comment]
I get the same issue with nexus 5x android nougat/O. can't get a 1:1 setting it with a setAspectRatio call after layout. Is there an update to this problem?

**Comment by drottemberg** [comment]
I had the same issue and basically you need to set the aspect ratio after the camera has been initialized in this function

```private CameraView.Callback mCallback
            = new CameraView.Callback() {

        @Override
        public void onCameraOpened(CameraView cameraView) {
            Set s = mCameraView.getSupportedAspectRatios(); // This is just to make sure the set is not empty
            mCameraView.setAspectRatio(AspectRatio.of(1,1));
        }
```

**Comment by jgarcia3327** [comment]
Do you guys have a fix on the issue? Have white background appearing on my Nexus 5x running Android 8 on 16:9 preview. All other phone I tested running ok. Thanks.

**Comment by nawinkhatiwada** [comment]
could not achieve aspect ratio 1:1 on Nokia 6

**Comment by Himanshu507** [comment]
> Do you guys have a fix on the issue? Have white background appearing on my Nexus 5x running Android 8 on 16:9 preview. All other phone I tested running ok. Thanks.

Hey can you help me. i'm recording the video on full screen but when i preview this video it not plays in full screen why ?
