### ISSUE TITLE
Is this projects still maintained ?

### ISSUE THREAD

**Issue by phukhanhlee** [google/cameraview#210]
I want to reuse this camera lib for my project but I see a lot of issues and pull request. So Is this project still maintained ?

**Comment by sibelius** [comment]
@yaraki what is the status of this cameraview?

**Comment by yaraki** [comment]
I'm still maintaining this project, but right now, I'm occupied with other projects.

**Comment by alexshikov** [comment]
Hey @yaraki , I have some ideas for PRs, but as far as I see there are a lot of PRs and issues that stuck in the pending mode.
Are there any plans for support? Does it make sense to make effort to contribute?
