### ISSUE TITLE
when capture image it get shifted to the left

### ISSUE THREAD

**Issue by MoustafaElsaghier** [google/cameraview#238]
when I try to use **front** camera and capture image then I get extra image section that I don't need it to be displayed. 

my camera view is 200*300 dp and I get more than 200 when the load on the image the array of byte.

any help?

**Comment by HemanthImandi** [comment]
Facing same issue. Any solution?

**Comment by HemanthImandi** [comment]
put the height of the cameraview as wrap_content

**Comment by MoustafaElsaghier** [comment]
nope i just used `app:cameraCropOutput="true"` in the XML of cameraview
