### ISSUE TITLE
Just Turn ON Flash Light without capturing

### ISSUE THREAD

**Issue by amira133** [google/cameraview#248]
Hello
I want to know how turn on flash light without taking picture. Or set it to turn On flash light all the time.

Thank..

**Comment by LuisBurgos** [comment]
One way you could interact with the flash light is by using the method `CameraView#setFlash(int)`:

```java
cameraView.setFlash(CameraView.FLASH_TORCH);
```

Note: Be sure to use `CameraView.FLASH_TORCH` instead of `CameraView.FLASH_ON` to force the flash light to be on all the time.
