### ISSUE TITLE
 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by but455** [google/cameraview#249]
Session has been closed; further changes are illegal.

com.google.android.cameraview.Camera2.lockFocus(Camera2.java:587)

1 android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:666)
--
2 android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:172)
3 com.google.android.cameraview.Camera2.lockFocus(Camera2.java:587)
4 com.google.android.cameraview.Camera2.takePicture(Camera2.java:338)
5 com.google.android.cameraview.CameraView.takePicture(CameraView.java:409)
6 com.cgbchina.ChinaLife.plugin.customCamera.CustomCameraActivity.shutter(CustomCameraActivity.java:228)
7 com.cgbchina.ChinaLife.plugin.customCamera.CustomCameraActivity.onClick(CustomCameraActivity.java:153)

**Comment by jjn2004** [comment]
do you find the solution  ?
