### ISSUE TITLE
Does it support recording pause in API 14?

### ISSUE THREAD

**Issue by meunicorn** [google/cameraview#26]
Does it support recording pause in API 14? or i have to use the high level MediaRecorder to do that?

**Comment by yaraki** [comment]
What's recording pause?

**Comment by meunicorn** [comment]
If user are recording a 5 minutes long video , sometimes user may want to pause the recording , and i found lots of camera doesn't support pause the recording . So i wonder if the cameraview can support this function.(And sorry for my poor English)

**Comment by yaraki** [comment]
CameraView does not yet support video recording. Let me see if I can add that pause feature when we have video recording support.

**Comment by meunicorn** [comment]
@yaraki Thanks for your replay~!
