### ISSUE TITLE
Prefix library attributes

### ISSUE THREAD

**Issue by hvisser** [google/cameraview#4]
Because android attributes are shared in a common namespace, it's a good habit to prefix attributes like `aspectRatio` in order to prevent conflicts with other libraries that a project may use.

I'd suggest prefixing the attributes this library adds with `cam` or `cv` for example so that `app:aspectRatio` would become `app:camAspectRatio` or `app:cvAspectRatio`.

**Comment by chrisbanes** [comment]
> Because android attributes are **currently** shared in a common namespace

**Comment by hvisser** [comment]
I'm not sure how far we are from `aapt2` being a thing, but I can live with that :) Filed this mainly on my experience with other libs that had clashing attributes, which is a painful experience, so I'll close this then.
