### ISSUE TITLE
Result File is Strange

### ISSUE THREAD

**Issue by FongMi** [google/cameraview#59]
This is Preview in App.
![device-2016-12-06-163137](https://cloud.githubusercontent.com/assets/3471963/20918416/db1ba692-bbd1-11e6-9bd0-850ee04c83a7.png)

This is Result File.
![htct1_20161206163146](https://cloud.githubusercontent.com/assets/3471963/20918445/00e53384-bbd2-11e6-8dcd-80afc81a7781.jpg)

Why the result picture is dark ??

Device OS version: 6.0.1
Devide Manufacturer: HTC
Device Name: HTC_M910X

**Comment by yaraki** [comment]
Nice keyboard. I suppose this is a device-dependent issue with the flash.

**Comment by DinoMC** [comment]
I have the same issue on a Sony Xperia Z3. I don't have a picture of the preview, but here's the result file : 
![test](https://cloud.githubusercontent.com/assets/9079110/26703065/26fba9f4-4728-11e7-8aa5-c8687f52ce27.jpg)

This is in daylight, with good lighting, and the flash didn't trigger (which is normal in those conditions). Could this still be an issue with the flash?

It works fine on my other devices.
