### ISSUE TITLE
How to import this library into project?

### ISSUE THREAD

**Issue by mladenrakonjac** [google/cameraview#60]
Couse there is no jcenter, how I can import this?

**Comment by PavelSynek** [comment]
https://jitpack.io/#google/cameraview

**Comment by mladenrakonjac** [comment]
I get this error :
Gradle sync failed: Could not find com.github.google:cameraview:-SNAPSHOT

**Comment by PavelSynek** [comment]
I wouldn't use SNAPSHOT, it might lead to unpredictable builds. `compile 'com.github.google:cameraview:d0b508a5ea'` works for me.

**Comment by mladenrakonjac** [comment]
I got same error

**Comment by PavelSynek** [comment]
Oh you also need to add `maven { url 'https://jitpack.io' }` to the project-level `build.gradle`

**Comment by yaraki** [comment]
#10

**Comment by dbarretto** [comment]
If you are having issues importing this library please check this link below:

http://stackoverflow.com/questions/32718820/failed-to-resolve-com-github-philjaympandroidchartv2-1-4/37892027#37892027
