### ISSUE TITLE
question about autofocusing.

### ISSUE THREAD

**Issue by pastafarianGit** [google/cameraview#66]
hey,
When I try to implement this library, autofocus doesn't work. I basically copied MainActivity from git into my project. Only thing i added to that is  app:autoFocus="true" to CameraView. But it's still won't autofocus even though when i installed demoapp apk on same device it works perfectly.

Check difference in this [link](https://docs.google.com/drawings/d/1N04UGXC89FcZOysQLsLHJ8oANKEZlCZqIDcJ8F8TJC0/edit?usp=sharing).

Any tips would be greatly appreciated!

**Comment by yaraki** [comment]
Auto focus should be on by default. Can you share other part of your code?

**Comment by pastafarianGit** [comment]
My bad, I don't think it was problem with autofocus. Problem probably lies in parameters for previewBuilder.
CaptureRequest.Builder mPreviewRequestBuilder;
mPreviewRequestBuilder.set();

You can remove this question. Thanks for time!
