### ISSUE TITLE
How to Stop take pictures ? it will auto take a lot of pictures ?

### ISSUE THREAD

**Issue by PigFlyy** [google/cameraview#75]

**Comment by n0m0r3pa1n** [comment]
You app is probably using the Camera1 API and the FOCUS_MODE_CONTINUOUS_PICTURE. You have to edit the Camera1 class and update it to look like this:
`
 void takePictureInternal() {
        mCamera.takePicture(null, null, null, new Camera.PictureCallback() {
            @Override
            public void onPictureTaken(byte[] data, Camera camera) {
                mCallback.onPictureTaken(data);
                camera.cancelAutoFocus();
                camera.startPreview();
            }
        });
    }
`
