### ISSUE TITLE
match_parent problem

### ISSUE THREAD

**Issue by mladenrakonjac** [google/cameraview#78]
<com.google.android.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        /> 

This works fine, but it does not fill full screen. When I take picture, picture has same sizes and aspect ratio as view.(I think it is 4:3) 

 Than, I decided to go with full screen:

<com.google.android.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        /> 

This is full screen, but when I take a picture, the picture has same size and aspectRatio as the previous one 4:3 and not 9:16 (full screen view aspect ratio).

**Comment by JakeWoki** [comment]
@yaraki 
Can auto to select aspectRatio in CameraView initialize when match_parent?
