### ISSUE TITLE
Stop camera 

### ISSUE THREAD

**Issue by protocol10** [google/cameraview#79]
This library does not have function to show preview of the snapshot taken, is there any way we can do that

**Comment by tobiaszolejnik** [comment]
Hi! What about this issue?
I want to stop camera after picture was taken and see a preview.

**Comment by stonkamutant** [comment]
Hi! What about this issue?
I want to stop camera after picture was taken and see a picture preview instead of a running camera.

**Comment by TommyFen** [comment]
#158 
it has been fixed.
