### ISSUE TITLE
Why Using camera1 for all api than what is meaning of camera 2

### ISSUE THREAD

**Issue by deepikaopenxcell** [google/cameraview#83]

**Comment by n0m0r3pa1n** [comment]
Have you tried using the limited Camera2 API on device that does not support it fully? Believe it or not, there are devices with Android 5 & 6 which do not support Camera2 API fully. So, you decide to take a picture with a flash and you get a crash. I think this sounds reasonable enough.

**Comment by yaraki** [comment]
There are some features that are only available in Camera2. I intend to support them in the future with some graceful degradation on Camera1 devices.
