### ISSUE TITLE
Capture photo is bigger than the preview image

### ISSUE THREAD

**Issue by saran2somu** [google/cameraview#92]
I have added the camera view in between my header and footer  layout. I have captured only previewed (half) image but finally I got full image . I want only preview image (half).

**Comment by xp-vit** [comment]
Library will give you full image and you need to crop image yourself. Here is nice article on making Square images:
https://kylewbanks.com/blog/tutorial-square-camera-with-preview-on-android

Take a closer look at: `private Bitmap processImage`

**Comment by saran2somu** [comment]
Thanks a lot @xp-vit t .. I will look into that tutorial
